[2022-07-01 04:37:02,778] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-07-01T04:36:59.216671+00:00 [queued]>
[2022-07-01 04:37:02,787] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-07-01T04:36:59.216671+00:00 [queued]>
[2022-07-01 04:37:02,787] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-01 04:37:02,787] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-01 04:37:02,787] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-01 04:37:02,793] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): accurate> on 2022-07-01 04:36:59.216671+00:00
[2022-07-01 04:37:02,796] {standard_task_runner.py:52} INFO - Started process 4374 to run task
[2022-07-01 04:37:02,799] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2022-07-01T04:36:59.216671+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/second_1.py', '--cfg-path', '/tmp/tmptd2iomvi', '--error-file', '/tmp/tmpun3hcke1']
[2022-07-01 04:37:02,800] {standard_task_runner.py:80} INFO - Job 38: Subtask accurate
[2022-07-01 04:37:02,833] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate manual__2022-07-01T04:36:59.216671+00:00 [running]> on host cb1ba423fa3f
[2022-07-01 04:37:02,866] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-01T04:36:59.216671+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-01T04:36:59.216671+00:00
[2022-07-01 04:37:02,866] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-01 04:37:02,867] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-07-01 04:37:02,873] {subprocess.py:85} INFO - Output:
[2022-07-01 04:37:02,874] {subprocess.py:89} INFO - accurate
[2022-07-01 04:37:02,874] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-01 04:37:02,889] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220701T043659, start_date=20220701T043702, end_date=20220701T043702
[2022-07-01 04:37:02,931] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-01 04:37:02,964] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
